name: core_authenticator
description: This package provides functions for authentication.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.3

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.12
  riverpod_generator: 2.4.3
  yumemi_lints: 2.2.0
