name: 'Deploy docs'
description: 'Deploy document site for Cloudflare Pages'

inputs:
  project-name:
    description: 'The name of the project'
    required: true
  branch:
    description: 'The branch to deploy'
    required: true
  cloudflare-account-id:
    description: 'The Cloudflare account ID'
    required: true
  cloudflare-api-token:
    description: 'The Cloudflare API token'
    required: true
outputs:
  deployment-url:
    description: 'The URL of the deployment'
    value: ${{ steps.cloudflare-pages.outputs.deployment-url }}

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@943808f3f14bac3770a312c0bb13666971d502c1 # v2.1.3

    - name: Install deps
      shell: bash
      run: bun install

    - name: Build
      run: bun run build
      shell: bash
      working-directory: ./docs

    # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@b2a0191ce60d21388e1a8dcc968b4e9966f938e1 # v3.11.0
      id: cloudflare-pages
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        command: >
          pages deploy ./docs/dist
          --project-name=${{ inputs.project-name }}
          --branch=${{ inputs.branch }}
