name: core_domain
description: This package provides use cases and domain models.
publish_to: "none"

environment:
  sdk: 3.5.0

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_data:
    path: ../data
  core_model:
    path: ../model
  freezed_annotation: 2.4.4
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.12
  core_testing:
    path: ../testing
  freezed: 2.5.7
  riverpod_generator: 2.4.2
  test: 1.25.8
  yumemi_lints: 2.2.0
