name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  catalog:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2.1.1

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Build
        run: flutter build web --release
        working-directory: app/catalog

      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@39c2b5a1226e5718f92a2749a8988cce31e78a76 # v3.10.0
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy ./app/catalog/build/web
            --project-name=torchro-app-catalog
            --branch=main
