name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  catalog:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Build
        run: flutter build web --release
        working-directory: app/catalog

      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@6d58852c35a27e6034745c5d0bc373d739014f7f # v3.13.0
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy ./app/catalog/build/web
            --project-name=torchro-app-catalog
            --branch=main
