name: 'Checks'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    uses: ./.github/workflows/wc-changes.yml

  action:
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.action == 'true'
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/actionlint-with-reviewdog
      - uses: reviewdog/action-actionlint@534eb894142bcf31616e5436cbe4214641c58101 # v1.61.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          fail_on_error: true
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  cache-deps:
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.dependencies == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10

      - name: setup pub
        uses: ./.github/actions/setup-pub

  analyze:
    runs-on: ubuntu-24.04
    needs:
      - changes
      - cache-deps
    if: needs.changes.outputs.analyze == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Run analyze
        run: melos analyze

  test:
    runs-on: ubuntu-24.04
    needs:
      - changes
      - cache-deps
    if: needs.changes.outputs.test == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Setup very_good_cli
        run: dart pub global activate very_good_cli

      - name: Run test
        run: melos run ci:test --no-select

  status-check:
    runs-on: ubuntu-24.04
    needs:
      - action
      - analyze
      - test
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
