name: "Pull Request Labeler"

on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      # https://github.com/marketplace/actions/label-manager-for-prs-and-issues-based-on-configurable-conditions
      - name: Label manager for PRs and Issues based on configurable conditions
        uses: srvaroa/labeler@29471ee1118fa4e10b011964e6e8fe2fd243e700 # v1.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tatsutakeinjp-bot:
    if: github.event.pull_request.user.login == 'tatsutakeinjp-bot[bot]'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Add labels to PR
        run: |
          gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: 'ignore for release'
