name: 'Lint Pull Request Title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

concurrency:
  group: semantic-pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: 'Semantic Pull Request'
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/semantic-pull-request
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
