name: 'Slash Commands Comment'

on:
  pull_request_target:
    types:
      - opened

concurrency:
  group: slash-command-comment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commands-comment:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/comment-pull-request
      - uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Commands

            | Command  | Description                                        |
            |----------|----------------------------------------------------|
            | /catalog | この Pull Request の Catalog を Cloudflare Pages にデプロイ |
            | /gen     | コード生成コマンドを実行し、変更があればコミットする                         |
          comment_tag: slash-command
          mode: upsert
