name: "Catalog Preview"

on:
  workflow_call:
    inputs:
      gh-app-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true
      cloudflare-account-id:
        required: true
      cloudflare-api-token:
        required: true

concurrency:
  group: catalog-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ inputs.gh-app-id }}
          private-key: ${{ secrets.gh-app-private-key }}

      # https://github.com/marketplace/actions/comment-pull-request
      - uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying torchro-app-catalog with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            :dancer: Now building ${{ github.sha }} ... :dancer:

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment_tag: deploy-catalog-preview
          mode: upsert

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2.1.8

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Build
        run: flutter build web --release
        working-directory: app/catalog

      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@6d58852c35a27e6034745c5d0bc373d739014f7f # v3.13.0
        id: deploy
        with:
          apiToken: ${{ secrets.cloudflare-api-token }}
          accountId: ${{ secrets.cloudflare-account-id }}
          command: >
            pages deploy ./app/catalog/build/web
            --project-name=torchro-app-catalog
            --branch=preview

      # https://github.com/marketplace/actions/comment-pull-request
      - if: steps.deploy.outcome == 'success'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying torchro-app-catalog with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            <table><tr><td><strong>Latest commit:</strong> </td><td>
            ${{ github.sha }} ${{ github.event.pull_request.head.sha && format('(i.e. {0} on {1})', github.event.pull_request.head.sha, 'preview') || '' }}
            </td></tr>
            <tr><td><strong>Status:</strong></td><td>&nbsp;✅&nbsp; Deploy successful!</td></tr>
            <tr><td><strong>Preview URL:</strong></td><td>
            <a href='${{ steps.deploy.outputs.deployment-url }}'>${{ steps.deploy.outputs.deployment-url }}</a>
            </td></tr>
            </table>

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment_tag: deploy-catalog-preview
          mode: recreate

      # https://github.com/marketplace/actions/comment-pull-request
      - if: failure()
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying torchro-app-catalog with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            <table><tr><td><strong>Latest commit:</strong> </td><td>
            ${{ github.sha }}
            </td></tr>
            <tr><td><strong>Status:</strong></td><td>&nbsp;:warning:&nbsp; ${{ steps.deploy.outcome == 'failure' && 'Deploy' || '**Job**' }} failure!</td></tr>
            </table>

            Check the run result and/or Cloudflare Pages.

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment_tag: deploy-catalog-preview
          mode: recreate
